name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Enable Corepack & prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create .env for CI
        run: |
          echo "PORT=3000" > .env
          echo "NODE_ENV=test" >> .env
          echo "DATABASE_URL=file:./dev.db" >> .env

      - name: Prisma generate
        run: npx prisma generate

      - name: Prisma migrate (deploy)
        run: npx prisma migrate deploy

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test
