name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: |
          npm i -g pnpm@10
          pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create .env for CI
        run: |
          echo "PORT=3000" > .env
          echo "NODE_ENV=test" >> .env
          echo "DATABASE_URL=file:./dev.db" >> .env

      - name: Prisma generate
        run: npx prisma generate

      - name: Prisma migrate (deploy)
        run: npx prisma migrate deploy

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

  docker-image:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Viktigt: QEMU krävs för att kunna bygga andra arkitekturer (arm64 på amd64 runners)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=long
            type=sha,format=short
            type=ref,event=branch
            type=raw,enable=${{ github.ref == 'refs/heads/main' }},value=latest

      - name: Print pushed tags (preview)
        run: echo "${{ steps.meta.outputs.tags }}"

      # Multi-arch build + push
      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
